using System;
public static class LuaWapBinder
{
	public static void Bind(IntPtr L)
	{
		WrapCallBack.Register(L);
		WrapIState.Register(L);
		WrapObjectPool.Register(L);
		WrapStateManager.Register(L);
		WrapDebugging.Register(L);
		WrapInputManager.Register(L);
		WrapResourcesManager.Register(L);
		WrapScreenControl.Register(L);
		WrapScreenControl.Register(L);
		WrapTimerManager.Register(L);
		WrapUIManager.Register(L);
		WrapEntity.Register(L);
		WrapFSMBase.Register(L);
		WrapStateBase.Register(L);
		WrapAnimationComponent.Register(L);
		WrapMovmentComponent.Register(L);
		WrapGamePublic.Register(L);
		WrapGlobalConfig.Register(L);
		WrapDataManager.Register(L);
		WrapKingInfo.Register(L);
		WrapCityInfo.Register(L);
		WrapGeneralInfo.Register(L);
		WrapGameStatesManager.Register(L);
		WrapInternalAffairsState.Register(L);
		WrapLoadingState.Register(L);
		WrapSelectKingState.Register(L);
		WrapSelectTimesState.Register(L);
		WrapStartMenuState.Register(L);
		WrapMapCameraControl.Register(L);
		WrapPathFinding.Register(L);
		WrapUtility.Register(L);
		WrapUIButton.Register(L);
		WrapXMLConfigPath.Register(L);
		WrapXMLManager.Register(L);
		WrapXMLDataArms.Register(L);
		WrapXMLDataBuff.Register(L);
		WrapXMLDataCity.Register(L);
		WrapXMLDataCityPoints.Register(L);
		WrapXMLDataFormations.Register(L);
		WrapXMLDataGenerals.Register(L);
		WrapXMLDataGlobalConfig.Register(L);
		WrapXMLDataKings.Register(L);
		WrapXMLDataMagic.Register(L);
		WrapXMLDataObjects.Register(L);
		WrapXMLDataPathInfo.Register(L);
		WrapXMLDataPeriod.Register(L);
		WrapXMLLoader_XMLDataArms.Register(L);
		WrapXMLLoader_XMLDataBuff.Register(L);
		WrapXMLLoader_XMLDataCity.Register(L);
		WrapXMLLoader_XMLDataCityPoints.Register(L);
		WrapXMLLoader_XMLDataFormations.Register(L);
		WrapXMLLoader_XMLDataGenerals.Register(L);
		WrapXMLLoader_XMLDataGlobalConfig.Register(L);
		WrapXMLLoader_XMLDataKings.Register(L);
		WrapXMLLoader_XMLDataMagic.Register(L);
		WrapXMLLoader_XMLDataObjects.Register(L);
		WrapXMLLoader_XMLDataPathInfo.Register(L);
		WrapXMLLoader_XMLDataPeriod.Register(L);
		WrapTestLuaFunctionType.Register(L);
	}
}
