using System;
public static class LuaWapBinder
{
	public static void Bind(IntPtr L)
	{
		WrapCallBack.Register(L);
		WrapIState.Register(L);
		WrapObjectPool.Register(L);
		WrapStateManager.Register(L);
		WrapDebugging.Register(L);
		WrapInputManager.Register(L);
		WrapResourcesManager.Register(L);
		WrapScreenControl.Register(L);
		WrapScreenControl.Register(L);
		WrapTimerManager.Register(L);
		WrapUIManager.Register(L);
		WrapEntity.Register(L);
		WrapFSMBase.Register(L);
		WrapStateBase.Register(L);
		WrapAnimationComponent.Register(L);
		WrapMovmentComponent.Register(L);
		WrapGamePublic.Register(L);
		WrapGlobalConfig.Register(L);
		WrapDataManager.Register(L);
		WrapKingInfo.Register(L);
		WrapCityInfo.Register(L);
		WrapGeneralInfo.Register(L);
		WrapGameStatesManager.Register(L);
		WrapInternalAffairsState.Register(L);
		WrapLoadingState.Register(L);
		WrapSelectKingState.Register(L);
		WrapSelectTimesState.Register(L);
		WrapStartMenuState.Register(L);
		WrapMapCameraControl.Register(L);
		WrapPathFinding.Register(L);
		WrapUtility.Register(L);
		WrapUIButton.Register(L);
		WrapXMLConfigPath.Register(L);
		WrapXMLManager.Register(L);
		WrapXMLDataBattle.Register(L);
		WrapXMLDataCity.Register(L);
		WrapXMLDataForce.Register(L);
		WrapXMLDataGenerals.Register(L);
		WrapXMLDataKings.Register(L);
		WrapXMLDataLanguage.Register(L);
		WrapXMLDataMagic.Register(L);
		WrapXMLDataMenuItem.Register(L);
		WrapXMLDataThings.Register(L);
		WrapXMLDataTimes.Register(L);
		WrapXMLDataWiseSkill.Register(L);
		WrapXMLDataPathInfo.Register(L);
		WrapXMLDataCityPoints.Register(L);
		WrapXMLLoader_XMLDataBattle.Register(L);
		WrapXMLLoader_XMLDataCity.Register(L);
		WrapXMLLoader_XMLDataForce.Register(L);
		WrapXMLLoader_XMLDataGenerals.Register(L);
		WrapXMLLoader_XMLDataKings.Register(L);
		WrapXMLLoader_XMLDataLanguage.Register(L);
		WrapXMLLoader_XMLDataMagic.Register(L);
		WrapXMLLoader_XMLDataMenuItem.Register(L);
		WrapXMLLoader_XMLDataThings.Register(L);
		WrapXMLLoader_XMLDataTimes.Register(L);
		WrapXMLLoader_XMLDataWiseSkill.Register(L);
		WrapXMLLoader_XMLDataPathInfo.Register(L);
		WrapXMLLoader_XMLDataCityPoints.Register(L);
		WrapTestLuaFunctionType.Register(L);
	}
}
